Websites/Mini proj/MiniProject01/StudentProgManagment/Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StudentProgManagment.Models;

namespace StudentProgManagment.Controllers
{
    public class ProjectsController : Controller
    {
        // GET: ProjectsController
        public ActionResult Index()
        {
            int? id = HttpContext.Session.GetInt32("id");

            if (id > 0)
            {
                return View(Projects.GetProjectsByStudentId(id));
            }

            return RedirectToAction("Create", "Login");
        }

        // GET: ProjectsController/Details/5
        public ActionResult Details(int id)
        {
            int? sid = HttpContext.Session.GetInt32("id");

            if (sid > 0)
            {
                return View(Projects.GetProjectsById(id));
            }

            return RedirectToAction("Create", "Login");

            
        }

        // GET: ProjectsController/Create
        public ActionResult Create()
        {
            int? id = HttpContext.Session.GetInt32("id");
            if (id > 0)
            {
                return View();
            }

            return RedirectToAction("Create", "Login");
         
        }

        // POST: ProjectsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection, Projects project)
        {
            try
            {
                Projects.InsertProjects(project);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProjectsController/Edit/5
        public ActionResult Edit(int id)
        {
            int? sid = HttpContext.Session.GetInt32("id");

            if (sid > 0)
            {
                return View(Projects.GetProjectsById(id));
            }

            return RedirectToAction("Create", "Login");
            
        }

        // POST: ProjectsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection, Projects project)
        {
            try
            {
                Projects.UpdateProject(project);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProjectsController/Delete/5
        public ActionResult Delete(int id)
        {
            int? sid = HttpContext.Session.GetInt32("id");

            if (sid > 0)
            {
                return View(Projects.GetProjectsById(id));
            }

            return RedirectToAction("Create", "Login");
            
        }

        // POST: ProjectsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int ProjectId, IFormCollection collection)
        {
            try
            {
                Projects.DeleteProject(ProjectId);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Websites/Mini proj/MiniProject01/StudentProgManagment/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using StudentProgManagment.Models;
//using StudentProgManagment.ViewModel;

namespace StudentProgManagment.Controllers
{
    public class StudentsController : Controller
    {
        // GET: StudentsController
        public ActionResult Index()
        {
            return View(Students.GetAllStudent());
        }

        // GET: StudentsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: StudentsController/Create
        public ActionResult Create()
        {
            StudentsViewModel studentsViewModel = new StudentsViewModel();
            List<SelectListItem> city = City.getAllCity();

            studentsViewModel.City = city;

            return View(studentsViewModel);
        }

        // POST: StudentsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection, Students stud)
        {
            try
            {
                Students.InsertStudent(stud);
                return RedirectToAction("Create", "Login");
                //return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: StudentsController/Edit/5
        public ActionResult Edit(int id)
        {
            int? sid = HttpContext.Session.GetInt32("id");
            StudentsViewModel stud = new StudentsViewModel();
            Students s = Students.GetStudentById(sid);

            List<SelectListItem> lst = City.getAllCity();

            stud.UserName = s.UserName;
            stud.StudentId = s.StudentId;
            stud.FullName= s.FullName;
            stud.Gender = s.Gender;
            stud.EmailId = s.EmailId;
            stud.CityId = s.CityId;
            stud.Password = s.Password;
            stud.Phone = s.Phone;
            stud.City= lst;

            return View(stud);
        }

        // POST: StudentsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection, Students students)
        {
            try
            {
                Students.UpdateStudent(students);
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        // GET: StudentsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: StudentsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Websites/Mini proj/MiniProject01/StudentProgManagment/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Students Projects Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StudentProgManagment.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StudentsProjectsManagement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @{
                            int? id = HttpContextAccessor.HttpContext.Session.GetInt32("id");
                            
                            string aid = HttpContextAccessor.HttpContext.Session.GetString("id");
                             if(aid!=null && aid.Equals("admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                                </li>
                            }
                               else if (id > 0)
                            {
                                <li class="nav-item">
                                 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Edit">Edit Profile</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="Index">Projects</a>
                                </li>
                                                               

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Create">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Create">Register</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                            }
                            
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - StudentProgManagment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>